### ISSUE TITLE
Kiiroo

### ISSUE THREAD

**Issue by g420000** [defucilis/funscript-io#20]
How do u add kiiroo keon to the site I wanna use mine with it but seems like u csn only use the handy

**Comment by defucilis** [comment]
Yes, the site only works with Handy, I'm afraid. I've thought about adding buttplug.io support, but it would basically require a full rewrite, and I don't have a compatible device so I'm not keen to do it. Partially because it'd be basically impossible to test without a device, and partially because adding support for such a device would provide zero benefit to me! :P

**Comment by g420000** [comment]
Just make it so it can run thru x toys or interface central

**Comment by defucilis** [comment]
XToys + Initface run on Buttplug, which is what I mentioned in my comment. I'd love to support more devices, but it would basically mean starting the entire project over from scratch. Since it wouldn't benefit me at all (since I have a Handy), I'm not super keen to devote weeks of full-time work to it.

That said, the project is open-source so if you'd like to use the funscript.io frontend layout, but write your own backend/device integration layer to support buttplug.io, I'll definitely help you in any way that I can :)

**Comment by g420000** [comment]
Let me put it this way I have 0 clue what imvdoing whenvit come to any of that hell half of what u just said was another language
